### ISSUE TITLE
Cannot compile on Debian stable

### ISSUE THREAD

**Issue by BlueMax** [Pteridium/U-boot_Lantiq_Danube#2]
Hi,
it breaks with this error. Any idea what could be wrong? Do i need different c headers maybe? Debian stable comes with glibc 2.13. 
Latest Barrier Breaker needs lzma patch and i'm trying to patch your uboot version. But it doesn't even compile here. Maybe Debian stable's libc is too old. I don't know. 
Or can you release a new compiled version?

Making all in mklibs-readelf
make[7]: Entering directory `/home/user/U-boot_Lantiq_Danube/build_dir/host/mklibs/src/mklibs-readelf'
x86_64-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../..   -O2 -I/home/user/U-boot_Lantiq_Danube/staging_dir/host/include -I/home/risk64/U-boot_Lantiq_Danube/tools/mklibs/include  -O2 -MT elf.o -MD -MP -MF .deps/elf.Tpo -c -o elf.o elf.cpp
elf.cpp: In static member function 'static Elf::file* Elf::file::open(const char*)':
elf.cpp:68:5: error: '::close' has not been declared
make[7]: *** [elf.o] Error 1
make[7]: Leaving directory`/home/user/U-boot_Lantiq_Danube/build_dir/host/mklibs/src/mklibs-readelf'
make[6]: **\* [all-recursive] Error 1
make[6]: Leaving directory `/home/user/U-boot_Lantiq_Danube/build_dir/host/mklibs/src'
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory`/home/user/U-boot_Lantiq_Danube/build_dir/host/mklibs'
make[4]: **\* [all] Error 2
make[4]: Leaving directory `/home/user/U-boot_Lantiq_Danube/build_dir/host/mklibs'
make[3]: *** [/home/user/U-boot_Lantiq_Danube/build_dir/host/mklibs/.built] Error 2
make[3]: Leaving directory`/home/user/U-boot_Lantiq_Danube/tools/mklibs'
make[2]: **\* [tools/mklibs/compile] Error 2
make[2]: Leaving directory `/home/user/U-boot_Lantiq_Danube'
make[1]: *** [/home/user/U-boot_Lantiq_Danube/staging_dir/target-mips_r2_uClibc-0.9.32/stamp/.tools_install_nnnnn] Error 2
make[1]: Leaving directory`/home/user/U-boot_Lantiq_Danube'
make: **\* [world] Error 2

**Comment by Pteridium** [comment]
Fixed (I hope so).
